services:
  - type: web
    name: oakandfinchinteractive
    runtime: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.19.0
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
